{
  lib,
  stdenv,
  stdenvNoCC,
  autoPatchelfHook,
  buildGoModule,
  copyDesktopItems,
  fetchurl,
  flutter,
  gtk3,
  keybinder3,
  libayatana-appindicator,
  libcap,
  makeDesktopItem,
  makeWrapper,
  pkg-config,
  runCommand,
  xdg-utils,
}:

let
  appVersionLine = lib.findFirst (lib.hasPrefix "version: ") "version: 0.0.0" (
    lib.splitString "\n" (builtins.readFile ../pubspec.yaml)
  );
  appVersion = lib.removePrefix "version: " appVersionLine;

  coreVersionLine = lib.findFirst (lib.hasInfix "var Version") "" (
    lib.splitString "\n" (builtins.readFile ../core/constant/version.go)
  );
  coreVersion = builtins.head (builtins.match ".*\"([^\"]+)\".*" coreVersionLine);

  flutterJs = runCommand "pub-flutter_js-0.8.3"
    {
      src = fetchurl {
        url = "https://github.com/chen08209/flutter_js/archive/c0e10a5dab0e22cd616ec92ae71471d76369cbfe.tar.gz";
        hash = "sha256-+YF86KA0z/6eXIdoPLtlN/leC/i24YCHWJg0rsS2mY8=";
      };
      passthru.packageRoot = ".";
    }
    ''
      mkdir -p "$out"
      tar --strip-components=1 -xzf "$src" -C "$out"
    '';

  core = buildGoModule {
    pname = "meowclash-core";
    version = appVersion;

    src = lib.cleanSource ../core;

    vendorHash = "sha256-5V/SpdLe8GUEDu2GsZ5zPP8vujkYVPqwwVhp+wywcFs=";

    env.CGO_ENABLED = "0";

    tags = [
      "with_gvisor"
      "cmfa"
    ];

    ldflags = [
      "-w"
      "-s"
      "-X"
      "github.com/metacubex/mihomo/constant.Version=${coreVersion}"
    ];

    postInstall = ''
      mv "$out/bin/core" "$out/bin/MeowClashCore"
    '';

    doCheck = false;

    meta = {
      description = "MeowClash mihomo core bridge";
      mainProgram = "MeowClashCore";
      platforms = lib.platforms.linux;
    };
  };
in
flutter.buildFlutterApplication rec {
  pname = "meowclash";
  version = appVersion;

  src = lib.cleanSourceWith {
    src = ../.;
    filter =
      path: type:
      let
        name = baseNameOf path;
      in
      !(lib.elem name [
        ".dart_tool"
        ".git"
        "build"
        "dist"
        "flutter_distributor"
        "libclash"
      ]);
  };

  pubspecLock = lib.importJSON ./pubspec.lock.json;

  customSourceBuilders.flutter_js = { ... }: flutterJs;

  flutterBuildFlags = [
    "--dart-define=APP_ENV=stable"
    "--dart-define=CORE_VERSION=${coreVersion}"
  ];

  nativeBuildInputs = [
    autoPatchelfHook
    copyDesktopItems
    makeWrapper
    pkg-config
  ];

  buildInputs = [
    gtk3
    keybinder3
    libayatana-appindicator
    stdenv.cc.cc.lib
  ];

  preBuild = ''
    mkdir -p libclash/linux
    ln -sf ${core}/bin/MeowClashCore libclash/linux/MeowClashCore

    cat > lib/core_version.dart <<'EOF'
    // GENERATED by nix/package.nix from core/constant/version.go - do not edit by hand
    // ignore_for_file: constant_identifier_names

    /// Embedded mihomo version (see core/constant/version.go).
    const String kCoreVersionFromSource = '${coreVersion}';
    EOF
  '';

  postInstall = ''
    rm -f "$out/bin/MeowClashCore"

    install -Dm444 assets/images/icon.png \
      "$out/share/icons/hicolor/512x512/apps/meowclash.png"
  '';

  desktopItems = [
    (makeDesktopItem {
      name = "meowclash";
      desktopName = "MeowClash";
      exec = "meowclash";
      icon = "meowclash";
      comment = meta.description;
      terminal = false;
      categories = [ "Network" ];
    })
  ];

  extraWrapProgramArgs = ''
    --set MEOWCLASH_NIX_PACKAGE 1 \
    --set MEOWCLASH_AUTOSTART_PATH meowclash \
    --set MEOWCLASH_CORE_PATH MeowClashCore \
    --prefix PATH : /run/wrappers/bin:${lib.makeBinPath [
      core
      libcap
      xdg-utils
    ]}
  '';

  passthru = {
    inherit core;

    pubspecSource = stdenvNoCC.mkDerivation {
      pname = "meowclash-pubspec-lock-json";
      inherit version src;
      nativeBuildInputs = [ ];
      dontBuild = true;
      installPhase = ''
        cp ${./pubspec.lock.json} "$out"
      '';
    };
  };

  meta = {
    description = "Multi-platform Flutter proxy client wrapping mihomo";
    homepage = "https://github.com/Loischsiy/MeowClash";
    license = lib.licenses.gpl3Only;
    mainProgram = "meowclash";
    platforms = [ "x86_64-linux" ];
  };
}
