// GENERATED by setup.dart from zapret/version.go — do not edit by hand
// ignore_for_file: constant_identifier_names

/// Bundled zapret2 engine version (see zapret/version.go).
const String kZapret2VersionFromSource = 'v1.0.2';
