// Generates offline country display names from Node's bundled ICU/Unicode CLDR.
// No runtime/package dependency or network request is needed by the app.
// Unicode data license: https://www.unicode.org/license.txt
// Run from the repository root: node tool/generate_ip_country_names.cjs
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const locales = fs.readdirSync(path.join(root, 'arb'))
  .filter((name) => /^intl_.+\.arb$/.test(name))
  .sort()
  .map((name) => name.slice(5, -4).replaceAll('_', '-'));
const english = new Intl.DisplayNames(['en'], {type: 'region', fallback: 'code'});
const codes = [];
for (let a = 65; a <= 90; a++) {
  for (let b = 65; b <= 90; b++) {
    const code = String.fromCharCode(a, b);
    if (code !== 'ZZ' && english.of(code) !== code) codes.push(code);
  }
}
const quote = (text) => JSON.stringify(text).replaceAll('$', '\\$');
let output = `// GENERATED by tool/generate_ip_country_names.cjs; do not edit by hand.
// Unicode CLDR country names (ICU ${process.versions.icu}).
// See docs/licenses/unicode.txt for the Unicode data license.

/// ISO country code -> the selected APP language, independent of API/browser
/// language. Unknown codes return null so the UI can use a localized placeholder.
String? localizedIpCountryName(String countryCode, String languageCode) {
  final code = countryCode.trim().toUpperCase();
  final language = languageCode.toLowerCase().split(RegExp('[-_]')).first;
  return (_ipCountryNames[language] ?? _ipCountryNames['en'])?[code];
}

const _ipCountryNames = <String, Map<String, String>>{\n`;
for (const locale of locales) {
  if (!Intl.DisplayNames.supportedLocalesOf([locale]).length) {
    throw new Error(`Missing ICU locale: ${locale}`);
  }
  const names = new Intl.DisplayNames([locale], {type: 'region', fallback: 'code'});
  output += `  ${quote(locale.split('-')[0])}: {\n`;
  for (const code of codes) output += `    ${quote(code)}: ${quote(names.of(code))},\n`;
  output += '  },\n';
}
output += '};\n';
fs.writeFileSync(path.join(root, 'lib/common/ip_country_names.dart'), output);
console.log(`Generated ${codes.length} countries for ${locales.length} locales (ICU ${process.versions.icu})`);
