display_name: MeowClash
package_name: MeowClash
maintainer:
  name: pluralplay
  email: mail@pluralplay.rw

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - MeowClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: MeowClash

categories:
  - Network

startup_notify: true